// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuleStreet.Data;

#nullable disable

namespace RuleStreet.Data.Migrations
{
    [DbContext(typeof(RuleStreetAppContext))]
    [Migration("20240407163345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RuleStreet.Models.Ciudadano", b =>
                {
                    b.Property<int>("IdCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCiudadano"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBusquedaYCaptura")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPeligroso")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPoli")
                        .HasColumnType("bit");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCuentaBancaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroTelefono")
                        .HasColumnType("int");

                    b.HasKey("IdCiudadano");

                    b.ToTable("Ciudadano");

                    b.HasData(
                        new
                        {
                            IdCiudadano = 1,
                            Apellidos = "Perez",
                            Direccion = "Calle Falsa 123",
                            Dni = "12345678",
                            FechaNacimiento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Hombre",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Español",
                            Nombre = "Juan",
                            NumeroCuentaBancaria = "ES123456789",
                            NumeroTelefono = 123456789
                        },
                        new
                        {
                            IdCiudadano = 2,
                            Apellidos = "Gonzalez",
                            Direccion = "Calle Falsa 123",
                            Dni = "87654321",
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Mujer",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Española",
                            Nombre = "Maria",
                            NumeroCuentaBancaria = "ES987654321",
                            NumeroTelefono = 987654321
                        });
                });

            modelBuilder.Entity("RuleStreet.Models.Multa", b =>
                {
                    b.Property<int>("IdMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMulta"));

                    b.Property<string>("ArticuloPenal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CiudadanoIdCiudadano")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCiudadano")
                        .HasColumnType("int");

                    b.Property<int>("IdPolicia")
                        .HasColumnType("int");

                    b.Property<bool>("Pagada")
                        .HasColumnType("bit");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMulta");

                    b.HasIndex("CiudadanoIdCiudadano");

                    b.HasIndex("IdPolicia");

                    b.ToTable("Multa");
                });

            modelBuilder.Entity("RuleStreet.Models.Policia", b =>
                {
                    b.Property<int>("IdPolicia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPolicia"));

                    b.Property<int>("IdCiudadano")
                        .HasColumnType("int");

                    b.Property<string>("NumeroPlaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rango")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPolicia");

                    b.HasIndex("IdCiudadano");

                    b.ToTable("Policia");
                });

            modelBuilder.Entity("RuleStreet.Models.Multa", b =>
                {
                    b.HasOne("RuleStreet.Models.Ciudadano", null)
                        .WithMany("Multas")
                        .HasForeignKey("CiudadanoIdCiudadano");

                    b.HasOne("RuleStreet.Models.Policia", "Policia")
                        .WithMany()
                        .HasForeignKey("IdPolicia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policia");
                });

            modelBuilder.Entity("RuleStreet.Models.Policia", b =>
                {
                    b.HasOne("RuleStreet.Models.Ciudadano", "Ciudadano")
                        .WithMany()
                        .HasForeignKey("IdCiudadano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudadano");
                });

            modelBuilder.Entity("RuleStreet.Models.Ciudadano", b =>
                {
                    b.Navigation("Multas");
                });
#pragma warning restore 612, 618
        }
    }
}
