// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuleStreet.Data;

#nullable disable

namespace RuleStreet.Data.Migrations
{
    [DbContext(typeof(RuleStreetAppContext))]
    partial class RuleStreetAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RuleStreet.Models.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdPolicia")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdPolicia");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("RuleStreet.Models.Ayuntamiento", b =>
                {
                    b.Property<int>("IdUsuarioAyuntamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioAyuntamiento"));

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuarioAyuntamiento");

                    b.ToTable("Ayuntamiento");

                    b.HasData(
                        new
                        {
                            IdUsuarioAyuntamiento = 1,
                            Contrasena = "1234",
                            Dni = "12345678"
                        },
                        new
                        {
                            IdUsuarioAyuntamiento = 2,
                            Contrasena = "1234",
                            Dni = "87654321"
                        });
                });

            modelBuilder.Entity("RuleStreet.Models.Ciudadano", b =>
                {
                    b.Property<int>("IdCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCiudadano"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsBusquedaYCaptura")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPeligroso")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPoli")
                        .HasColumnType("bit");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCuentaBancaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroTelefono")
                        .HasColumnType("int");

                    b.HasKey("IdCiudadano");

                    b.ToTable("Ciudadano");

                    b.HasData(
                        new
                        {
                            IdCiudadano = 1,
                            Apellidos = "Gimenez Garulo",
                            Direccion = "Calle Falsa 123",
                            Dni = "12345678A",
                            FechaNacimiento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Hombre",
                            ImagenUrl = "https://lh3.googleusercontent.com/a-/ALV-UjW8BqiphgAP2RarwrIgqXMdH0Y4XWQgicOFG6g5lTSoqlharjkl=s75-c",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Española",
                            Nombre = "Alejadro",
                            NumeroCuentaBancaria = "ES123456789",
                            NumeroTelefono = 123456789
                        },
                        new
                        {
                            IdCiudadano = 2,
                            Apellidos = "Llorente Pinzon",
                            Direccion = "Calle Falsa 123",
                            Dni = "12345678B",
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Mujer",
                            ImagenUrl = "https://lh3.googleusercontent.com/a-/ALV-UjXq4SaB_ODyUUzUulLF9MsBbfp2kyQ8dJQ6-k96AxVcHx8PtnV2=s75-c",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Española",
                            Nombre = "Vanessa",
                            NumeroCuentaBancaria = "ES987654321",
                            NumeroTelefono = 987654321
                        },
                        new
                        {
                            IdCiudadano = 3,
                            Apellidos = "Crespo",
                            Direccion = "Calle Falsa 123",
                            Dni = "12345678C",
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Mujer",
                            ImagenUrl = "https://lh3.googleusercontent.com/a-/ALV-UjXNudiq8hrsLIIP4y9gHaPvdatUtONrCGpmKvYBTePbSFleNrs=s75-c",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Española",
                            Nombre = "Maria",
                            NumeroCuentaBancaria = "ES987654321",
                            NumeroTelefono = 987654321
                        },
                        new
                        {
                            IdCiudadano = 4,
                            Apellidos = "Hierro Amon",
                            Direccion = "Calle Falsa 123",
                            Dni = "12345678D",
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Hombre",
                            ImagenUrl = "https://lh3.googleusercontent.com/a/ACg8ocL5B2wDSyuywLri2wQOKXk9DuqWrYHjH0iShHT3uwZUSfnIqA=s32-c-mo",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Española",
                            Nombre = "Oliver",
                            NumeroCuentaBancaria = "ES987654321",
                            NumeroTelefono = 987654321
                        },
                        new
                        {
                            IdCiudadano = 5,
                            Apellidos = "Pardos Gotor",
                            Direccion = "Calle Falsa 123",
                            Dni = "12345678E",
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Hombre",
                            ImagenUrl = "https://lh3.googleusercontent.com/a-/ALV-UjXzV-jm0U5kV0lccfpkdR_NeIDpJRa3av9cA6fBJySmh8B-nsfU=s75-c",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Española",
                            Nombre = "Santos",
                            NumeroCuentaBancaria = "ES987654321",
                            NumeroTelefono = 987654321
                        },
                        new
                        {
                            IdCiudadano = 6,
                            Apellidos = "Higelmo Martinez",
                            Direccion = "Calle Falsa 123",
                            Dni = "12345678F",
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Mujer",
                            ImagenUrl = "https://lh3.googleusercontent.com/a-/ALV-UjWbaN_SMJT8GbltNzC69AJquU6hlO2JoVkXGBjpptldvZNclstX=s75-c",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Española",
                            Nombre = "Eva Maria",
                            NumeroCuentaBancaria = "ES987654321",
                            NumeroTelefono = 987654321
                        },
                        new
                        {
                            IdCiudadano = 7,
                            Apellidos = "Guardingo De La Riva",
                            Direccion = "Calle Falsa 123",
                            Dni = "12345678G",
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Mujer",
                            ImagenUrl = "https://lh3.googleusercontent.com/a-/ALV-UjW6IGDJ5YeNx1nJ1XnWsYBo15QF_E8JrIA9mMZ2uq9xQTI0XoY=s75-c",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Española",
                            Nombre = "Silvia",
                            NumeroCuentaBancaria = "ES987654321",
                            NumeroTelefono = 987654321
                        },
                        new
                        {
                            IdCiudadano = 8,
                            Apellidos = "Ruiz Lite",
                            Direccion = "Calle Falsa 123",
                            Dni = "12345678H",
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Hombre",
                            ImagenUrl = "https://lh3.googleusercontent.com/a-/ALV-UjV2lVzVGBSS8cX-TisA7tu5Guwo9KVK9aAalgSJzmqRZw629sc=s32-c",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Española",
                            Nombre = "Joaquin",
                            NumeroCuentaBancaria = "ES987654321",
                            NumeroTelefono = 987654321
                        });
                });

            modelBuilder.Entity("RuleStreet.Models.CodigoPenal", b =>
                {
                    b.Property<int>("IdCodigoPenal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCodigoPenal"));

                    b.Property<string>("Articulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sentencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCodigoPenal");

                    b.ToTable("CodigoPenal");

                    b.HasData(
                        new
                        {
                            IdCodigoPenal = 1,
                            Articulo = "Art. 1.1",
                            Descripcion = "Uso excesivo del claxón",
                            Precio = 500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 2,
                            Articulo = "Art. 1.2",
                            Descripcion = "Giro indebido",
                            Precio = 300m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 3,
                            Articulo = "Art. 1.3",
                            Descripcion = "Circular en sentido contrario",
                            Precio = 700m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 4,
                            Articulo = "Art. 1.4",
                            Descripcion = "Estacionar en zonas no habitadas y obstruir la circulación",
                            Precio = 500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 5,
                            Articulo = "Art. 1.5",
                            Descripcion = "Ignorar señales de tránsito",
                            Precio = 500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 6,
                            Articulo = "Art. 1.6",
                            Descripcion = "Saltarse un semáforo",
                            Precio = 450m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 7,
                            Articulo = "Art. 1.7",
                            Descripcion = "No ceder el paso a vehículos de emergencia",
                            Precio = 550m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 8,
                            Articulo = "Art. 1.8",
                            Descripcion = "Realizar adelantamiento indebido",
                            Precio = 350m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 9,
                            Articulo = "Art. 1.9",
                            Descripcion = "Circular marcha atrás",
                            Precio = 800m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 10,
                            Articulo = "Art. 1.10",
                            Descripcion = "Ignorar señales de los agentes que regulan la circulacion",
                            Precio = 500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 11,
                            Articulo = "Art. 1.11",
                            Descripcion = "Saltarse / omitir un control de trafico",
                            Precio = 500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 12,
                            Articulo = "Art. 1.12",
                            Descripcion = "Conducir un vehiculo en malas condiciones",
                            Precio = 1000m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 13,
                            Articulo = "Art. 1.13",
                            Descripcion = "Exceso de velocidad en vias urbanas",
                            Precio = 800m,
                            Sentencia = "5 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 14,
                            Articulo = "Art. 1.14",
                            Descripcion = "Condución temeraria",
                            Precio = 1500m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 15,
                            Articulo = "Art. 1.15",
                            Descripcion = "Exceso de velocidad en vias secundarias",
                            Precio = 1000m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 16,
                            Articulo = "Art. 1.16",
                            Descripcion = "Conducir bajo los efectos de drogas/alcohol",
                            Precio = 1500m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 17,
                            Articulo = "Art. 1.17",
                            Descripcion = "Circular por zonas no habilitadas para ello",
                            Precio = 1000m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 18,
                            Articulo = "Art. 1.18",
                            Descripcion = "Circular sin casco para motocicleta",
                            Precio = 500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 19,
                            Articulo = "Art. 1.18.1",
                            Descripcion = "Circular sin licencia de conducir",
                            Precio = 550m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 20,
                            Articulo = "Art. 2.1",
                            Descripcion = "Alteración del orden público",
                            Precio = 3500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 21,
                            Articulo = "Art. 2.2",
                            Descripcion = "Racismo",
                            Precio = 5000m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 22,
                            Articulo = "Art. 2.3",
                            Descripcion = "Faltas de respeto a otro civil",
                            Precio = 2500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 23,
                            Articulo = "Art. 2.4",
                            Descripcion = "Dañar mobiliario urbano",
                            Precio = 1700m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 24,
                            Articulo = "Art. 2.5",
                            Descripcion = "Acoso psicológico",
                            Precio = 6000m,
                            Sentencia = "5 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 25,
                            Articulo = "Art. 2.6",
                            Descripcion = "Amenaza de muerte a un civil",
                            Precio = 2000m,
                            Sentencia = "5 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 26,
                            Articulo = "Art. 2.7",
                            Descripcion = "Suplantación de identidad",
                            Precio = 6000m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 27,
                            Articulo = "Art. 2.8",
                            Descripcion = "Circular por la via pública con el rostro oculto",
                            Precio = 1000m,
                            Sentencia = "5 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 28,
                            Articulo = "Art. 2.9",
                            Descripcion = "Circular en la via pública desnudo o semi-desnudo",
                            Precio = 1200m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 29,
                            Articulo = "Art. 2.10",
                            Descripcion = "Circular en la via pública sin camiseta",
                            Precio = 120m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 30,
                            Articulo = "Art. 2.11",
                            Descripcion = "Acoso sexual",
                            Precio = 30000m,
                            Sentencia = "100 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 31,
                            Articulo = "Art. 2.12",
                            Descripcion = "Violar una orden de alejamiento con sentencia firme",
                            Precio = 25000m,
                            Sentencia = "80 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 32,
                            Articulo = "Art. 2.13",
                            Descripcion = "Negativa a identificarse",
                            Precio = 1000m,
                            Sentencia = "7 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 33,
                            Articulo = "Art. 2.14",
                            Descripcion = "Obstrucción a la justicia",
                            Precio = 2500m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 34,
                            Articulo = "Art. 3.1",
                            Descripcion = "Posesion de estupefacientes (marihuana) 210/unidad (a partir de 2 unidades)",
                            Precio = 210m,
                            Sentencia = "7 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 35,
                            Articulo = "Art. 3.2",
                            Descripcion = "Consumo de marihuana en vía pública",
                            Precio = 350m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 36,
                            Articulo = "Art. 3.3",
                            Descripcion = "Posesion de estupefacientes (Cocaína/Mentafetamina) 650/unidad (a partir de 2 unidades)",
                            Precio = 650m,
                            Sentencia = "7 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 37,
                            Articulo = "Art. 3.4",
                            Descripcion = "Se considera trafico de drogas a cualquier individuo o grupo de personas que se vean vendiendo estupefacientes en flagante delito. Multa de 450 por cada delito flagante de venta de cocaina. Se requisara todo el dinero que lleve el sujeto.",
                            Precio = 450m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 38,
                            Articulo = "Art. 3.5",
                            Descripcion = "Se considera trafico de drogas a cualquier individuo o grupo de personas que se vean vendiendo estupefacientes en flagante delito. Multa de 650 por cada delito flagante de venta de meta. Se requisara todo el dinero que lleve el sujeto.",
                            Precio = 650m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 39,
                            Articulo = "Art. 4.1",
                            Descripcion = "Queda totalmente prohibida por parte de los civiles portar una pistolera como atuendo de modo decorativo",
                            Precio = 1500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 40,
                            Articulo = "Art. 4.2",
                            Descripcion = "Posesion de arma blanca: son considerados como tal, aquellas armas de filo cortante. Armas blancas susceptibles de ser usadas como arma ilegal: Cuchillo, Bate de beisbol, Palo de golf, Botella rota, Navaja, Machete",
                            Precio = 2500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 41,
                            Articulo = "Art. 4.3",
                            Descripcion = "Portar pistola de baja calibre (arma de fuego)",
                            Precio = 10000m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 42,
                            Articulo = "Art. 4.4",
                            Descripcion = "Portar armas automaticas de baja calibre/medio",
                            Precio = 24000m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 43,
                            Articulo = "Art. 4.5",
                            Descripcion = "Portar armas automaticas de alto calibre",
                            Precio = 40000m,
                            Sentencia = "15 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 44,
                            Articulo = "Art. 4.6",
                            Descripcion = "Trafico de armas",
                            Precio = 30000m,
                            Sentencia = "25 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 45,
                            Articulo = "Art. 4.7",
                            Descripcion = "Atentado terrorista",
                            Precio = 100000m,
                            Sentencia = "250 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 46,
                            Articulo = "Art. 4.8",
                            Descripcion = "Atentar contra la vida o integridad fisica de varios personas y/o funcionarios publicos mediante la organizacion armada de varios individuos",
                            Precio = 100000m,
                            Sentencia = "350 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 47,
                            Articulo = "Art. 5.1",
                            Descripcion = "Agresion a otro individuo",
                            Precio = 3000m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 48,
                            Articulo = "Art. 5.2",
                            Descripcion = "Intento de agresion a civil",
                            Precio = 1500m,
                            Sentencia = "5 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 49,
                            Articulo = "Art. 5.3",
                            Descripcion = "Intento de secuestro",
                            Precio = 2400m,
                            Sentencia = "15 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 50,
                            Articulo = "Art. 5.4",
                            Descripcion = "Secuestro a un individuo",
                            Precio = 3500m,
                            Sentencia = "15 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 51,
                            Articulo = "Art. 5.5",
                            Descripcion = "Intento de homicidio a un civil sin el uso de armas",
                            Precio = 4000m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 52,
                            Articulo = "Art. 5.6",
                            Descripcion = "Intento de homicidio a un civil con uso de armas de cualquier indole",
                            Precio = 6000m,
                            Sentencia = "20 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 53,
                            Articulo = "Art. 5.7",
                            Descripcion = "Intento de homicidio a multiples sin el uso de armas",
                            Precio = 5000m,
                            Sentencia = "15 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 54,
                            Articulo = "Art. 5.8",
                            Descripcion = "Intento de homicidio a multiples civiles con uso de armas de cualquier indole",
                            Precio = 7500m,
                            Sentencia = "15 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 55,
                            Articulo = "Art. 6.1",
                            Descripcion = "Amenazas, desobedencia e insultos: Tras la primera amision de la orden de un funcionario de policia, se le podra acumular al reo el monta econonico despues del primer aviso por cada falta de respeto o desacato.",
                            Precio = 300m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 56,
                            Articulo = "Art. 6.2",
                            Descripcion = "Insultar a un funcionario publico.",
                            Precio = 1700m,
                            Sentencia = "5 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 57,
                            Articulo = "Art. 6.3",
                            Descripcion = "Agresión o amenaza de muerte a un funcionario.",
                            Precio = 3400m,
                            Sentencia = "5 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 58,
                            Articulo = "Art. 6.4",
                            Descripcion = "Desacato",
                            Precio = 2000m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 59,
                            Articulo = "Art. 6.5",
                            Descripcion = "Huir de la justicia",
                            Precio = 1500m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 60,
                            Articulo = "Art. 6.6",
                            Descripcion = "Usurpacion de funciones publicas",
                            Precio = 10000m,
                            Sentencia = "15 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 61,
                            Articulo = "Art. 6.7",
                            Descripcion = "Falso testimonio",
                            Precio = 2000m,
                            Sentencia = "5 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 62,
                            Articulo = "Art. 6.8",
                            Descripcion = "Usurpacion de funcionarios publicos",
                            Precio = 10000m,
                            Sentencia = "15 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 63,
                            Articulo = "Art. 6.9",
                            Descripcion = "Secuestro a un funcionario",
                            Precio = 8000m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 64,
                            Articulo = "Art. 6.10",
                            Descripcion = "Amenazar a un funcionario publico a mano armada",
                            Precio = 3500m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 65,
                            Articulo = "Art. 6.11",
                            Descripcion = "Intento de homicidio a un funcionario publico",
                            Precio = 5500m,
                            Sentencia = "15 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 66,
                            Articulo = "Art. 6.12",
                            Descripcion = "Homicidio a un funcionario",
                            Precio = 9000m,
                            Sentencia = "20 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 67,
                            Articulo = "Art. 6.13",
                            Descripcion = "Homicidio a diferentes funcionarios",
                            Precio = 12500m,
                            Sentencia = "50 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 68,
                            Articulo = "Art. 6.14",
                            Descripcion = "Robo de secretos del estado",
                            Precio = 0m,
                            Sentencia = "5000 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 69,
                            Articulo = "Art. 6.15",
                            Descripcion = "Sera acusado de denuncia falsa aquel que registre una denucia ante el cuerpo policial a sabiendas de su falsedad",
                            Precio = 2500m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 70,
                            Articulo = "Art. 6.16",
                            Descripcion = "Actos de corrupcion por parte de un agente",
                            Precio = 0m,
                            Sentencia = "5000 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 71,
                            Articulo = "Art. 7.1",
                            Descripcion = "Robo de vehiculo",
                            Precio = 2000m,
                            Sentencia = "6 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 72,
                            Articulo = "Art. 7.2",
                            Descripcion = "Robo con intimidacion a un civil",
                            Precio = 3400m,
                            Sentencia = "8 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 73,
                            Articulo = "Art. 7.3",
                            Descripcion = "Robo con violencia a un civil",
                            Precio = 2600m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 74,
                            Articulo = "Art. 7.4",
                            Descripcion = "Hurto menor",
                            Precio = 1500m,
                            Sentencia = "5 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 75,
                            Articulo = "Art. 7.5",
                            Descripcion = "Robar pertenencias que se hallen en el interior de un vehiculo de via urbana o propiedad privada",
                            Precio = 2150m,
                            Sentencia = "7 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 76,
                            Articulo = "Art. 8.1",
                            Descripcion = "Celebracion de manifestaciones en lugares de transito publico sin haber sido autorizados",
                            Precio = 1000m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 77,
                            Articulo = "Art. 8.2",
                            Descripcion = "Cometer actos de vandalismo",
                            Precio = 1500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 78,
                            Articulo = "Art. 8.3",
                            Descripcion = "Hurto de un civil sin importar las posesiones robadas",
                            Precio = 3500m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 79,
                            Articulo = "Art. 8.4",
                            Descripcion = "Obstaculizar el desempeño y desarrollo de las funciones publicas y servicios de emergencia",
                            Precio = 2300m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 80,
                            Articulo = "Art. 8.5",
                            Descripcion = "Negarse a disolver una reunion o manifestacion tras haber sido previamente advertido por un funcionario publico",
                            Precio = 1600m,
                            Sentencia = "5 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 81,
                            Articulo = "Art. 8.6",
                            Descripcion = "Negarse a identificarse o aportar datos falsos que dificulten la accion policial",
                            Precio = 1500m,
                            Sentencia = "5 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 82,
                            Articulo = "Art. 8.7",
                            Descripcion = "Amenazar a un funcionario publico a mano armada",
                            Precio = 3500m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 83,
                            Articulo = "Art. 8.8",
                            Descripcion = "Exhibicionismo: El que realice actos de exhibicionismo delante de personas causandoles un perjuicio",
                            Precio = 5500m,
                            Sentencia = "10 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 84,
                            Articulo = "Art. 8.9",
                            Descripcion = "Sera acusado de extorsion aquel que, con intencion de beneficiarse, obligue a otro con violencia o intimidacion a realizar un acto que le perjudique economicamente",
                            Precio = 3000m,
                            Sentencia = "15 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 85,
                            Articulo = "Art. 8.10",
                            Descripcion = "Sera acusado de injuria aquel que diga de manera publica hechos falsos que humillen a otra persona",
                            Precio = 1200m,
                            Sentencia = "7 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 86,
                            Articulo = "Art. 8.11",
                            Descripcion = "Violacion de la intimidad aquel que acceda a cualquier tipo de propiedad o dispositivo de otro, sea digital o analogico. El articulo excluye a los funcionarios publicos por desempeño de sus labores de investigacion",
                            Precio = 2400m,
                            Sentencia = "7 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 87,
                            Articulo = "Art. 8.12",
                            Descripcion = "Sera acusado de tortura aquel que realice actos degradantes, ofensivos, dañinos o de similar a una persona",
                            Precio = 5600m,
                            Sentencia = "15 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 88,
                            Articulo = "Art. 8.13",
                            Descripcion = "Negarse a la identificacion ante un funcionario publico",
                            Precio = 1500m,
                            Sentencia = "0 meses"
                        });
                });

            modelBuilder.Entity("RuleStreet.Models.Denuncia", b =>
                {
                    b.Property<int>("IdDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDenuncia"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCiudadano")
                        .HasColumnType("int");

                    b.Property<int?>("IdPolicia")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDenuncia");

                    b.HasIndex("IdCiudadano");

                    b.HasIndex("IdPolicia");

                    b.ToTable("Denuncia");
                });

            modelBuilder.Entity("RuleStreet.Models.Evento", b =>
                {
                    b.Property<int>("IdEventos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEventos"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEventos");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("RuleStreet.Models.Multa", b =>
                {
                    b.Property<int>("IdMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMulta"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCiudadano")
                        .HasColumnType("int");

                    b.Property<int>("IdCodigoPenal")
                        .HasColumnType("int");

                    b.Property<int>("IdPolicia")
                        .HasColumnType("int");

                    b.Property<bool?>("Pagada")
                        .HasColumnType("bit");

                    b.HasKey("IdMulta");

                    b.HasIndex("IdCiudadano");

                    b.HasIndex("IdCodigoPenal");

                    b.HasIndex("IdPolicia");

                    b.ToTable("Multa");
                });

            modelBuilder.Entity("RuleStreet.Models.Nota", b =>
                {
                    b.Property<int>("IdNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNota"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCiudadano")
                        .HasColumnType("int");

                    b.Property<int?>("IdPolicia")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNota");

                    b.HasIndex("IdCiudadano");

                    b.HasIndex("IdPolicia");

                    b.ToTable("Nota");
                });

            modelBuilder.Entity("RuleStreet.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permiso");

                    b.HasData(
                        new
                        {
                            IdPermiso = 1,
                            Nombre = "Añadir policia"
                        },
                        new
                        {
                            IdPermiso = 2,
                            Nombre = "Quitar policia"
                        },
                        new
                        {
                            IdPermiso = 3,
                            Nombre = "Modificar policia"
                        },
                        new
                        {
                            IdPermiso = 4,
                            Nombre = "Borrar multa"
                        },
                        new
                        {
                            IdPermiso = 5,
                            Nombre = "Crear multa"
                        },
                        new
                        {
                            IdPermiso = 6,
                            Nombre = "Borrar denuncia"
                        },
                        new
                        {
                            IdPermiso = 7,
                            Nombre = "Crear denuncia"
                        },
                        new
                        {
                            IdPermiso = 8,
                            Nombre = "Modificar denuncia"
                        },
                        new
                        {
                            IdPermiso = 9,
                            Nombre = "Eliminar nota"
                        },
                        new
                        {
                            IdPermiso = 10,
                            Nombre = "Crear nota"
                        },
                        new
                        {
                            IdPermiso = 11,
                            Nombre = "Modificar nota"
                        },
                        new
                        {
                            IdPermiso = 12,
                            Nombre = "Crear evento"
                        },
                        new
                        {
                            IdPermiso = 13,
                            Nombre = "Eliminar evento"
                        });
                });

            modelBuilder.Entity("RuleStreet.Models.Policia", b =>
                {
                    b.Property<int>("IdPolicia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPolicia"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCiudadano")
                        .HasColumnType("int");

                    b.Property<int?>("IdRango")
                        .HasColumnType("int");

                    b.Property<string>("NumeroPlaca")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPolicia");

                    b.HasIndex("IdCiudadano");

                    b.HasIndex("IdRango");

                    b.ToTable("Policia");
                });

            modelBuilder.Entity("RuleStreet.Models.Rango", b =>
                {
                    b.Property<int>("IdRango")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRango"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Salario")
                        .HasColumnType("int");

                    b.Property<bool?>("isLocal")
                        .HasColumnType("bit");

                    b.HasKey("IdRango");

                    b.ToTable("Rango");

                    b.HasData(
                        new
                        {
                            IdRango = 1,
                            Nombre = "Practicas",
                            Salario = 1071,
                            isLocal = true
                        },
                        new
                        {
                            IdRango = 2,
                            Nombre = "Agente",
                            Salario = 1330,
                            isLocal = true
                        },
                        new
                        {
                            IdRango = 3,
                            Nombre = "Oficial I",
                            Salario = 1412,
                            isLocal = true
                        },
                        new
                        {
                            IdRango = 4,
                            Nombre = "Oficial II",
                            Salario = 1483,
                            isLocal = true
                        },
                        new
                        {
                            IdRango = 5,
                            Nombre = "Oficial III",
                            Salario = 1555,
                            isLocal = true
                        },
                        new
                        {
                            IdRango = 6,
                            Nombre = "Subinspector",
                            Salario = 1674,
                            isLocal = true
                        },
                        new
                        {
                            IdRango = 7,
                            Nombre = "Inspector",
                            Salario = 1765,
                            isLocal = true
                        },
                        new
                        {
                            IdRango = 8,
                            Nombre = "Inspector Jefe",
                            Salario = 1881,
                            isLocal = true
                        },
                        new
                        {
                            IdRango = 9,
                            Nombre = "Intendente",
                            Salario = 2028,
                            isLocal = true
                        },
                        new
                        {
                            IdRango = 10,
                            Nombre = "Superintendente",
                            Salario = 2142,
                            isLocal = true
                        });
                });

            modelBuilder.Entity("RuleStreet.Models.RangoPermiso", b =>
                {
                    b.Property<int>("IdRango")
                        .HasColumnType("int");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.HasKey("IdRango", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("RangoPermiso");

                    b.HasData(
                        new
                        {
                            IdRango = 1,
                            IdPermiso = 5
                        },
                        new
                        {
                            IdRango = 1,
                            IdPermiso = 7
                        },
                        new
                        {
                            IdRango = 2,
                            IdPermiso = 5
                        },
                        new
                        {
                            IdRango = 2,
                            IdPermiso = 7
                        },
                        new
                        {
                            IdRango = 2,
                            IdPermiso = 10
                        },
                        new
                        {
                            IdRango = 3,
                            IdPermiso = 5
                        },
                        new
                        {
                            IdRango = 3,
                            IdPermiso = 7
                        },
                        new
                        {
                            IdRango = 3,
                            IdPermiso = 10
                        },
                        new
                        {
                            IdRango = 3,
                            IdPermiso = 11
                        },
                        new
                        {
                            IdRango = 4,
                            IdPermiso = 5
                        },
                        new
                        {
                            IdRango = 4,
                            IdPermiso = 7
                        },
                        new
                        {
                            IdRango = 4,
                            IdPermiso = 10
                        },
                        new
                        {
                            IdRango = 4,
                            IdPermiso = 11
                        },
                        new
                        {
                            IdRango = 5,
                            IdPermiso = 5
                        },
                        new
                        {
                            IdRango = 5,
                            IdPermiso = 7
                        },
                        new
                        {
                            IdRango = 5,
                            IdPermiso = 10
                        },
                        new
                        {
                            IdRango = 5,
                            IdPermiso = 11
                        },
                        new
                        {
                            IdRango = 6,
                            IdPermiso = 5
                        },
                        new
                        {
                            IdRango = 6,
                            IdPermiso = 7
                        },
                        new
                        {
                            IdRango = 6,
                            IdPermiso = 8
                        },
                        new
                        {
                            IdRango = 6,
                            IdPermiso = 10
                        },
                        new
                        {
                            IdRango = 6,
                            IdPermiso = 11
                        },
                        new
                        {
                            IdRango = 7,
                            IdPermiso = 5
                        },
                        new
                        {
                            IdRango = 7,
                            IdPermiso = 7
                        },
                        new
                        {
                            IdRango = 7,
                            IdPermiso = 8
                        },
                        new
                        {
                            IdRango = 7,
                            IdPermiso = 9
                        },
                        new
                        {
                            IdRango = 7,
                            IdPermiso = 10
                        },
                        new
                        {
                            IdRango = 7,
                            IdPermiso = 11
                        },
                        new
                        {
                            IdRango = 8,
                            IdPermiso = 3
                        },
                        new
                        {
                            IdRango = 8,
                            IdPermiso = 5
                        },
                        new
                        {
                            IdRango = 8,
                            IdPermiso = 7
                        },
                        new
                        {
                            IdRango = 8,
                            IdPermiso = 8
                        },
                        new
                        {
                            IdRango = 8,
                            IdPermiso = 9
                        },
                        new
                        {
                            IdRango = 8,
                            IdPermiso = 10
                        },
                        new
                        {
                            IdRango = 8,
                            IdPermiso = 11
                        },
                        new
                        {
                            IdRango = 9,
                            IdPermiso = 1
                        },
                        new
                        {
                            IdRango = 9,
                            IdPermiso = 3
                        },
                        new
                        {
                            IdRango = 9,
                            IdPermiso = 4
                        },
                        new
                        {
                            IdRango = 9,
                            IdPermiso = 5
                        },
                        new
                        {
                            IdRango = 9,
                            IdPermiso = 6
                        },
                        new
                        {
                            IdRango = 9,
                            IdPermiso = 7
                        },
                        new
                        {
                            IdRango = 9,
                            IdPermiso = 8
                        },
                        new
                        {
                            IdRango = 9,
                            IdPermiso = 9
                        },
                        new
                        {
                            IdRango = 9,
                            IdPermiso = 10
                        },
                        new
                        {
                            IdRango = 9,
                            IdPermiso = 11
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 1
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 2
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 3
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 4
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 5
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 6
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 7
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 8
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 9
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 10
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 11
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 12
                        },
                        new
                        {
                            IdRango = 10,
                            IdPermiso = 13
                        });
                });

            modelBuilder.Entity("RuleStreet.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCiudadano")
                        .HasColumnType("int");

                    b.Property<int?>("IdPolicia")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPolicia")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("policiaIdPolicia")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdCiudadano")
                        .IsUnique()
                        .HasFilter("[IdCiudadano] IS NOT NULL");

                    b.HasIndex("policiaIdPolicia");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("RuleStreet.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCiudadano")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("IdCiudadano");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("RuleStreet.Models.Auditoria", b =>
                {
                    b.HasOne("RuleStreet.Models.Policia", "Policia")
                        .WithMany()
                        .HasForeignKey("IdPolicia");

                    b.Navigation("Policia");
                });

            modelBuilder.Entity("RuleStreet.Models.Denuncia", b =>
                {
                    b.HasOne("RuleStreet.Models.Ciudadano", "Ciudadano")
                        .WithMany()
                        .HasForeignKey("IdCiudadano");

                    b.HasOne("RuleStreet.Models.Policia", "Policia")
                        .WithMany()
                        .HasForeignKey("IdPolicia");

                    b.Navigation("Ciudadano");

                    b.Navigation("Policia");
                });

            modelBuilder.Entity("RuleStreet.Models.Multa", b =>
                {
                    b.HasOne("RuleStreet.Models.Ciudadano", "Ciudadano")
                        .WithMany("Multas")
                        .HasForeignKey("IdCiudadano");

                    b.HasOne("RuleStreet.Models.CodigoPenal", "CodigoPenal")
                        .WithMany("Multas")
                        .HasForeignKey("IdCodigoPenal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuleStreet.Models.Policia", "Policia")
                        .WithMany()
                        .HasForeignKey("IdPolicia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudadano");

                    b.Navigation("CodigoPenal");

                    b.Navigation("Policia");
                });

            modelBuilder.Entity("RuleStreet.Models.Nota", b =>
                {
                    b.HasOne("RuleStreet.Models.Ciudadano", "ciudadano")
                        .WithMany()
                        .HasForeignKey("IdCiudadano");

                    b.HasOne("RuleStreet.Models.Policia", "policia")
                        .WithMany()
                        .HasForeignKey("IdPolicia");

                    b.Navigation("ciudadano");

                    b.Navigation("policia");
                });

            modelBuilder.Entity("RuleStreet.Models.Policia", b =>
                {
                    b.HasOne("RuleStreet.Models.Ciudadano", "Ciudadano")
                        .WithMany()
                        .HasForeignKey("IdCiudadano");

                    b.HasOne("RuleStreet.Models.Rango", "Rango")
                        .WithMany("Policias")
                        .HasForeignKey("IdRango");

                    b.Navigation("Ciudadano");

                    b.Navigation("Rango");
                });

            modelBuilder.Entity("RuleStreet.Models.RangoPermiso", b =>
                {
                    b.HasOne("RuleStreet.Models.Permiso", "Permiso")
                        .WithMany("RangosPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuleStreet.Models.Rango", "Rango")
                        .WithMany("RangosPermisos")
                        .HasForeignKey("IdRango")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rango");
                });

            modelBuilder.Entity("RuleStreet.Models.Usuario", b =>
                {
                    b.HasOne("RuleStreet.Models.Ciudadano", "Ciudadano")
                        .WithOne("Usuario")
                        .HasForeignKey("RuleStreet.Models.Usuario", "IdCiudadano");

                    b.HasOne("RuleStreet.Models.Policia", "policia")
                        .WithMany()
                        .HasForeignKey("policiaIdPolicia");

                    b.Navigation("Ciudadano");

                    b.Navigation("policia");
                });

            modelBuilder.Entity("RuleStreet.Models.Vehiculo", b =>
                {
                    b.HasOne("RuleStreet.Models.Ciudadano", "Ciudadano")
                        .WithMany("Vehiculos")
                        .HasForeignKey("IdCiudadano");

                    b.Navigation("Ciudadano");
                });

            modelBuilder.Entity("RuleStreet.Models.Ciudadano", b =>
                {
                    b.Navigation("Multas");

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("RuleStreet.Models.CodigoPenal", b =>
                {
                    b.Navigation("Multas");
                });

            modelBuilder.Entity("RuleStreet.Models.Permiso", b =>
                {
                    b.Navigation("RangosPermisos");
                });

            modelBuilder.Entity("RuleStreet.Models.Rango", b =>
                {
                    b.Navigation("Policias");

                    b.Navigation("RangosPermisos");
                });
#pragma warning restore 612, 618
        }
    }
}
