// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuleStreet.Data;

#nullable disable

namespace RuleStreet.Data.Migrations
{
    [DbContext(typeof(RuleStreetAppContext))]
    partial class RuleStreetAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RuleStreet.Models.Ciudadano", b =>
                {
                    b.Property<int>("IdCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCiudadano"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsBusquedaYCaptura")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPeligroso")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPoli")
                        .HasColumnType("bit");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCuentaBancaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroTelefono")
                        .HasColumnType("int");

                    b.HasKey("IdCiudadano");

                    b.ToTable("Ciudadano");

                    b.HasData(
                        new
                        {
                            IdCiudadano = 1,
                            Apellidos = "Perez",
                            Direccion = "Calle Falsa 123",
                            Dni = "12345678",
                            FechaNacimiento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Hombre",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Español",
                            Nombre = "Juan",
                            NumeroCuentaBancaria = "ES123456789",
                            NumeroTelefono = 123456789
                        },
                        new
                        {
                            IdCiudadano = 2,
                            Apellidos = "Gonzalez",
                            Direccion = "Calle Falsa 123",
                            Dni = "87654321",
                            FechaNacimiento = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Mujer",
                            IsBusquedaYCaptura = false,
                            IsPeligroso = false,
                            IsPoli = false,
                            Nacionalidad = "Española",
                            Nombre = "Maria",
                            NumeroCuentaBancaria = "ES987654321",
                            NumeroTelefono = 987654321
                        });
                });

            modelBuilder.Entity("RuleStreet.Models.CodigoPenal", b =>
                {
                    b.Property<int>("IdCodigoPenal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCodigoPenal"));

                    b.Property<string>("Articulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sentencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCodigoPenal");

                    b.ToTable("CodigoPenal");

                    b.HasData(
                        new
                        {
                            IdCodigoPenal = 1,
                            Articulo = "Art. 1.1",
                            Descripcion = "Uso excesivo del claxón",
                            Precio = 500m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 2,
                            Articulo = "Art. 1.2",
                            Descripcion = "Giro indebido",
                            Precio = 300m,
                            Sentencia = "0 meses"
                        },
                        new
                        {
                            IdCodigoPenal = 3,
                            Articulo = "Art. 1.3",
                            Descripcion = "Circular en sentido contrario",
                            Precio = 700m,
                            Sentencia = "0 meses"
                        });
                });

            modelBuilder.Entity("RuleStreet.Models.Multa", b =>
                {
                    b.Property<int>("IdMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMulta"));

                    b.Property<string>("ArticuloPenal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CiudadanoIdCiudadano")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCiudadano")
                        .HasColumnType("int");

                    b.Property<int>("IdPolicia")
                        .HasColumnType("int");

                    b.Property<bool?>("Pagada")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMulta");

                    b.HasIndex("CiudadanoIdCiudadano");

                    b.HasIndex("IdPolicia");

                    b.ToTable("Multa");
                });

            modelBuilder.Entity("RuleStreet.Models.Policia", b =>
                {
                    b.Property<int>("IdPolicia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPolicia"));

                    b.Property<int?>("IdCiudadano")
                        .HasColumnType("int");

                    b.Property<string>("NumeroPlaca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rango")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPolicia");

                    b.HasIndex("IdCiudadano");

                    b.ToTable("Policia");
                });

            modelBuilder.Entity("RuleStreet.Models.Multa", b =>
                {
                    b.HasOne("RuleStreet.Models.Ciudadano", null)
                        .WithMany("Multas")
                        .HasForeignKey("CiudadanoIdCiudadano");

                    b.HasOne("RuleStreet.Models.Policia", "Policia")
                        .WithMany()
                        .HasForeignKey("IdPolicia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policia");
                });

            modelBuilder.Entity("RuleStreet.Models.Policia", b =>
                {
                    b.HasOne("RuleStreet.Models.Ciudadano", "Ciudadano")
                        .WithMany()
                        .HasForeignKey("IdCiudadano");

                    b.Navigation("Ciudadano");
                });

            modelBuilder.Entity("RuleStreet.Models.Ciudadano", b =>
                {
                    b.Navigation("Multas");
                });
#pragma warning restore 612, 618
        }
    }
}
