name: Despliegue en EKS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  EKS_CLUSTER_NAME: RuleStreetCluster
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Desplegar en EKS
    runs-on: ubuntu-latest
    steps:
      
name: Extraer código
      uses: actions/checkout@v2

      
name: Construir la imagen
      run: |
        docker build -t danielpalacios2003/rulestreetapi:latest .
        docker tag danielpalacios2003/rulestreetapi:latest  danielpalacios2003/rulestreetapi:${{ github.sha }}

      
name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

      
name: Enviar imagen a Docker Hub
      run: |
        docker push danielpalacios2003/rulestreetapi:latest
        docker push api:${{ github.sha }}

      
name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

      
name: Actualizar configuración de kubeconfig
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      
name: Desplegar en Kubernetes
      run: kubectl apply -f K8s/2-api-deployment.yml

      
name: Deploy to Kubernetes
      run: kubectl apply -f K8s/2-api-deployment.yml
